// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhdAqzC0edxNuFXybm2g23Vi0BhB2cJ_Q',
    appId: '1:951107304160:web:83c1f3e073e1a8b3322e85',
    messagingSenderId: '951107304160',
    projectId: 'collector-s-emporium',
    authDomain: 'collector-s-emporium.firebaseapp.com',
    storageBucket: 'collector-s-emporium.appspot.com',
    measurementId: 'G-4J6HXJ8YGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfzmjcxDflaQuZoygXFPa1nCFpOVPxAXM',
    appId: '1:951107304160:android:0576571e0cf0fe19322e85',
    messagingSenderId: '951107304160',
    projectId: 'collector-s-emporium',
    storageBucket: 'collector-s-emporium.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgHsRhg39hpS7wq6La6sDv6-rscbOwHDk',
    appId: '1:951107304160:ios:4881336aadccd1db322e85',
    messagingSenderId: '951107304160',
    projectId: 'collector-s-emporium',
    storageBucket: 'collector-s-emporium.appspot.com',
    iosBundleId: 'com.example.collectorsSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgHsRhg39hpS7wq6La6sDv6-rscbOwHDk',
    appId: '1:951107304160:ios:0d032ed6a2ce9e32322e85',
    messagingSenderId: '951107304160',
    projectId: 'collector-s-emporium',
    storageBucket: 'collector-s-emporium.appspot.com',
    iosBundleId: 'com.example.collectorsSocialMediaApp.RunnerTests',
  );
}
